name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install cython3 libwings-dev
      - name: Build
        run: |
          python3 setup.py test
      - name: Generate documentation
        run: make -C doc html
      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: doc/_build/html
